"""create attendance_sessions

Revision ID: 310f8f881393
Revises: b05d1f26abe9
Create Date: 2026-09-24 23:18:36.946346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310f8f881393'
down_revision: Union[str, Sequence[str], None] = 'b05d1f26abe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SUBMITTED', name='attendancesessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_sessions_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index('ix_attendance_sessions_section_date', ['section_id', 'session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_section_id'))
        batch_op.drop_index('ix_attendance_sessions_section_date')
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_faculty_id'))

    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
