"""create faculty and faculty_assignments

Revision ID: b05d1f26abe9
Revises: 9bcbb2da938c
Create Date: 2026-09-24 23:05:22.634220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05d1f26abe9'
down_revision: Union[str, Sequence[str], None] = '9bcbb2da938c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_faculty_user_id'), ['user_id'], unique=True)

    op.create_table('faculty_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_assignments_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('uq_faculty_assignment_active', ['faculty_id', 'subject_id', 'section_id', 'semester_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_faculty_assignment_active', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = true'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_subject_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_semester_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_section_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_faculty_id'))

    op.drop_table('faculty_assignments')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_user_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_employee_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_department_id'))

    op.drop_table('faculty')
    # ### end Alembic commands ###
